version: '3'
services:
  production-service-client:
    image: node:12
    volumes:
      - nodemodules:/usr/src/service/node_modules:consistent
      - ./../:/usr/src/service:consistent
    environment:
      - NODE_ENV=production
    working_dir: /usr/src/service
    command: npm run serve:production
    ports:
      - '{{local_machine.port}}:{{local_machine.port}}'
volumes:
  nodemodules:
    external: true
