version: '3'
services:
  development-service-client:
    image: node:12
    volumes:
      - nodemodules:/usr/src/service/node_modules:consistent
      - ./../:/usr/src/service:consistent
    environment:
      - NODE_ENV=development
    working_dir: /usr/src/service
    command: npm run serve:development
    ports:
      - {{port}}:{{port}}
volumes:
  nodemodules:
    external: true
