name: 'coverage'

on: [push]

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v1
      - uses: artiomtr/jest-coverage-report-action@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          test_script: npx jest --config .jestrc.json --silent --ci --coverage --coverageReporters="text" --coverageReporters="text-summary"
