name: Github CI [Build]

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        env:
          CI: true
      - run: docker volume create nodemodules
      - run: docker-compose -f ./.docker/docker-compose.commands.yml run --rm install
      - run: docker-compose -f ./.docker/docker-compose.commands.yml run --rm prepare
      - run: docker-compose -f ./.docker/docker-compose.commands.yml run --rm build_for_deployment
      - name: Build Release
        id: build_release
        uses: actions/create-release@v1
        with:
          tag_name: beta-${{ github.sha }}
          release_name: beta-release ${{ github.repository }}:${{ github.sha }}
          body: Authored by ${{ github.actor }}
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.build_release.outputs.upload_url }}
          asset_path: ./dist/.archive.zip
          asset_name: archive.zip
          asset_content_type: application/zip
